services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    image: blairchen123/quirknotes_backend:latest
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    ports: 
    - "27017:27017"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: backend
    image: blairchen123/quirknotes_frontend
    ports:
    - "3000:3000"